import { OnInit } from "@angular/core";
import { FormBuilder, FormGroup } from "@angular/forms";
import { LoginService } from "./login.service";
import { AuthService } from "angular2-social-login";
import { Router } from "@angular/router";
import { AccountVerificationService } from "../signup/accountVerification/accountVerification.service";
import { LoginAccount } from "../../classes/LoginAccount";
export declare class LoginComponent implements OnInit {
    private fb;
    private loginService;
    auth: AuthService;
    private router;
    private accountVerify;
    loginForm: FormGroup;
    success: boolean;
    error: boolean;
    wrongDetails: boolean;
    user: any;
    verificationStat: boolean;
    account: LoginAccount;
    captcha: string;
    constructor(fb: FormBuilder, loginService: LoginService, auth: AuthService, router: Router, accountVerify: AccountVerificationService);
    ngOnInit(): void;
    login: () => void;
    private processError(response);
    signInGoogle(provider: string): void;
    signInFacebook(provider: string): void;
    sendFacebookToken(): void;
    sendGoogleToken(): void;
    reload(): void;
    handleCorrectCaptcha($event: any): void;
    validLogin(): boolean;
}
